### ISSUE TITLE
Error: Cannot find module 'mime' on install

### ISSUE THREAD

**Issue by michaelwittig** [lloyd/node-toobusy#19]
When I try to npm install toobusy I get the following error with node > 0.10.10. It works with 0.10.10.

```
npm install toobusy
info trying registry request attempt 1 at 18:07:52
http GET https://registry.npmjs.org/toobusy
http 304 https://registry.npmjs.org/toobusy
npm WARN package.json toobusy@0.2.3 No repository field.
npm WARN package.json toobusy@0.2.3 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
info trying registry request attempt 1 at 18:07:55
http GET https://registry.npmjs.org/bindings/1.1.0
http 304 https://registry.npmjs.org/bindings/1.1.0

> toobusy@0.2.3 install /Users/projectx/Projects/test123/node_modules/toobusy
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'mime'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:338:15)
gyp ERR! stack     at Function.Module._load (module.js:280:25)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! stack     at require (module.js:380:17)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/request/index.js:29:12)
gyp ERR! stack     at Module._compile (module.js:456:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! stack     at Function.Module._load (module.js:312:12)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! System Darwin 12.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/projectx/Projects/test123/node_modules/toobusy
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm ERR! weird error 7
npm ERR! not ok code 0

```

**Comment by markstos** [comment]
Did you ever figure out the underlying cause?

**Comment by michaelwittig** [comment]
Hi Mark,

As far as I remember the problem was solved by a newer version of node-toobusy.

Are you using the latest version? which version of node are you running?

Michael

**Comment by markstos** [comment]
Thanks for the reply.

I was actually getting `Error: Cannot find module 'mime' on install ' on a
different project, and was trying to understand why. From searching that
phrase, a fair number of people have run into it, and often don't
understand why.... likely because the core issue has nothing to do with not
finding the`mime` module. In my case, I think I might have been run into
into some kind of a stale module cache issue.

On Thu, Jul 10, 2014 at 12:57 AM, Michael Wittig notifications@github.com
wrote:

> Hi Mark,
> 
> As far as I remember the problem was solved by a newer version of
> node-toobusy.
> 
> Are you using the latest version? which version of node are you running?
> 
> Michael
> 
> > Am 08.07.2014 um 22:13 schrieb Mark Stosberg notifications@github.com:
> > 
> > Did you ever figure out the underlying cause?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/lloyd/node-toobusy/issues/19#issuecomment-48565287.

## 

```
Mark Stosberg
Senior Systems Engineer
RideAmigos
```
